{% set name = "jupyter-releaser" %}
{% set version = "0.23.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_releaser-{{ version }}.tar.gz
  sha256: 745e1dc1c9774dc9a34dcc7d40a9c871e93fb3080173a3d2ac84161cfab9ce68

build:
  number: 0
  noarch: python
  entry_points:
    - jupyter-releaser = jupyter_releaser.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.0
  run:
    - build
    - check-manifest
    - click
    - ghapi
    - github-activity ~=0.2
    - hatchling >=1.0
    - importlib_resources
    - jsonschema >=3.0.1
    - packaging
    - pkginfo
    - pre-commit
    - pypiserver
    - pytest-check-links >=0.7
    - python >=3.7
    - requests
    - requests-cache
    - tbump >=6.7,<7
    - toml ~=0.10
    - twine

test:
  imports:
    - jupyter_releaser
    - jupyter_releaser.actions
  commands:
    - jupyter-releaser --help
  requires:
    - pip

about:
  home: https://jupyter.org
  summary: Jupyter Releaser for Python and/or npm packages.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - jtpio
