{% set name = "jupyter-releaser" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_releaser-{{ version }}.tar.gz
  sha256: b0b9f03b40ee4b5303040d233984fa44a8c02c2e91b672c63131e1f835481f19

build:
  number: 0
  noarch: python
  entry_points:
    - jupyter-releaser = jupyter_releaser.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.0
  run:
    - click
    - ghapi <=1.0.4
    - github-activity ~=0.2
    - pipx
    - importlib_resources
    - jsonschema >=3.0.1
    - mdformat
    - packaging
    - pkginfo
    - pypiserver
    - python >=3.7
    - requests
    - requests-cache
    - toml ~=0.10

test:
  imports:
    - jupyter_releaser
    - jupyter_releaser.actions
  commands:
    - jupyter-releaser --help
  requires:
    - pip

about:
  home: https://jupyter.org
  summary: Jupyter Releaser for Python and/or npm packages.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - jtpio
